import "Mahjong.dart";

Map<String, Tile> TileMap = {
  "Man1":Tile(1, "m"),
  "Man2":Tile(2, "m"),
  "Man3":Tile(3, "m"),
  "Man4":Tile(4, "m"),
  "Man5":Tile(5, "m"),
  "Man6":Tile(6, "m"),
  "Man7":Tile(7, "m"),
  "Man8":Tile(8, "m"),
  "Man9":Tile(9, "m"),
  "Sou1":Tile(1, "s"),
  "Sou2":Tile(2, "s"),
  "Sou3":Tile(3, "s"),
  "Sou4":Tile(4, "s"),
  "Sou5":Tile(5, "s"),
  "Sou6":Tile(6, "s"),
  "Sou7":Tile(7, "s"),
  "Sou8":Tile(8, "s"),
  "Sou9":Tile(9, "s"),
  "Pin1":Tile(1, "p"),
  "Pin2":Tile(2, "p"),
  "Pin3":Tile(3, "p"),
  "Pin4":Tile(4, "p"),
  "Pin5":Tile(5, "p"),
  "Pin6":Tile(6, "p"),
  "Pin7":Tile(7, "p"),
  "Pin8":Tile(8, "p"),
  "Pin9":Tile(9, "p"),
  "Ton":Tile(1, "z"),
  "Nan":Tile(2, "z"),
  "Shaa":Tile(3, "z"),
  "Pei":Tile(4, "z"),
  "Hatsu":Tile(5, "z"),
  "Chun":Tile(6, "z"),
  "Haku":Tile(7, "z")
};