import "Mahjong.dart";

Map<String, String> TileMap = {
  "1m": "Man1.png",
  "2m": "Man2.png",
  "3m": "Man3.png",
  "4m": "Man4.png",
  "5m": "Man5.png",
  "6m": "Man6.png",
  "7m": "Man7.png",
  "8m": "Man8.png",
  "9m": "Man9.png",
  "1s": "Sou1.png",
  "2s": "Sou2.png",
  "3s": "Sou3.png",
  "4s": "Sou4.png",
  "5s": "Sou5.png",
  "6s": "Sou6.png",
  "7s": "Sou7.png",
  "8s": "Sou8.png",
  "9s": "Sou9.png",
  "1p": "Pin1.png",
  "2p": "Pin2.png",
  "3p": "Pin3.png",
  "4p": "Pin4.png",
  "5p": "Pin5.png",
  "6p": "Pin6.png",
  "7p": "Pin7.png",
  "8p": "Pin8.png",
  "9p": "Pin9.png",
  "1z": "Ton.png",
  "2z": "Nan.png",
  "3z": "Shaa.png",
  "4z": "Pei.png",
  "5z": "Hatsu.png",
  "6z": "Chun.png",
  "7z": "Haku.png"
};